//! Length-limited canonical Huffman code construction + dynamic-block header.
//!
//! Port of libdeflate `vendor/libdeflate/lib/deflate_compress.c`:
//! `sort_symbols` / `build_tree` / `compute_length_counts` / `gen_codewords` /
//! `deflate_make_huffman_code` (~:846-1396, the counting-sort + stripped-tree +
//! APPROXIMATE length limiter), `reverse_codeword` (~:1104-1152), and the
//! dynamic-header machinery `deflate_compute_precode_items` /
//! `deflate_precompute_huffman_header` (~:1482-1631).
//!
//! Correctness contract: the produced code is canonical and length-limited, so
//! every nonzero-frequency symbol gets a decodable codeword and the Kraft sum
//! is <= 1.

use super::bitstream::BitWriter;
use super::tables::{
    DEFLATE_NUM_PRECODE_SYMS, MAX_PRE_CODEWORD_LEN, PRECODE_EXTRA_BITS, PRECODE_LENS_PERMUTATION,
};

/// Exact length-limited code length assignment (Katajainen et al.) — the
/// crown engine's (`parse::ultra`) huffman builder. Distinct from this
/// file's own APPROXIMATE libdeflate-style builder below; kept as a sibling
/// submodule rather than merged, per Stage A (structural move only).
pub mod katajainen;
/// Zopfli's own bit-length / entropy tree helpers, used by the crown engine.
pub mod tree;

const NUM_SYMBOL_BITS: u32 = 10;
const SYMBOL_MASK: u32 = (1 << NUM_SYMBOL_BITS) - 1;
const FREQ_MASK: u32 = !SYMBOL_MASK;
/// Largest codeword length any DEFLATE code can use (offset code, 15 bits).
const MAX_CODEWORD_LEN: usize = 15;

/// A canonical Huffman code: per-symbol length (0 = unused) and bit-reversed
/// codeword (right-justified, only the low `len` bits are meaningful).
#[derive(Clone)]
pub struct HuffmanCode {
    pub lens: Vec<u8>,
    pub codewords: Vec<u32>,
}

// ---- bit reversal (reverse_codeword) ----

/// `bitreverse_tab[]` from libdeflate (generated by gen_bitreverse_tab.py).
const BITREVERSE_TAB: [u8; 256] = {
    let mut t = [0u8; 256];
    let mut i = 0usize;
    while i < 256 {
        let mut v = 0u8;
        let mut b = 0u32;
        while b < 8 {
            if (i >> b) & 1 != 0 {
                v |= 1 << (7 - b);
            }
            b += 1;
        }
        t[i] = v;
        i += 1;
    }
    t
};

/// Reverse the low `len` bits of `codeword` (DEFLATE uses bit-reversed
/// codewords). `len <= 16`.
#[inline]
fn reverse_codeword(codeword: u32, len: u8) -> u32 {
    let cw = ((BITREVERSE_TAB[(codeword & 0xff) as usize] as u32) << 8)
        | (BITREVERSE_TAB[((codeword >> 8) & 0xff) as usize] as u32);
    cw >> (16 - len as u32)
}

// ---- heap sort over packed (freq<<10 | sym) entries ----

#[inline]
fn heapify_subtree(a: &mut [u32], length: usize, subtree_idx: usize) {
    // 1-based indices, so a[idx] maps to slice a[idx-1].
    let v = a[subtree_idx - 1];
    let mut parent_idx = subtree_idx;
    loop {
        let mut child_idx = parent_idx * 2;
        if child_idx > length {
            break;
        }
        if child_idx < length && a[child_idx] > a[child_idx - 1] {
            child_idx += 1;
        }
        if v >= a[child_idx - 1] {
            break;
        }
        a[parent_idx - 1] = a[child_idx - 1];
        parent_idx = child_idx;
    }
    a[parent_idx - 1] = v;
}

fn heapify_array(a: &mut [u32], length: usize) {
    let mut subtree_idx = length / 2;
    while subtree_idx >= 1 {
        heapify_subtree(a, length, subtree_idx);
        subtree_idx -= 1;
    }
}

/// Heapsort `a` in place (ascending). Port of `heap_sort`.
fn heap_sort(a: &mut [u32]) {
    let mut length = a.len();
    if length < 2 {
        return;
    }
    heapify_array(a, length);
    while length >= 2 {
        a.swap(length - 1, 0);
        length -= 1;
        heapify_subtree(a, length, 1);
    }
}

// ---- sort_symbols ----

/// Count-sort symbols by frequency (secondary: symbol value), packing
/// `sym | (freq << 10)` into `symout`. Zero-frequency symbols get `lens[sym]=0`.
/// Returns the number of used (nonzero-frequency) symbols.
fn sort_symbols(freqs: &[u32], lens: &mut [u8], symout: &mut [u32]) -> usize {
    let num_syms = freqs.len();
    let num_counters = num_syms;
    let mut counters = vec![0u32; num_counters];

    for &f in freqs.iter() {
        let idx = f.min((num_counters - 1) as u32) as usize;
        counters[idx] += 1;
    }

    // Make counters cumulative (ignoring counter 0 = zero-frequency symbols).
    let mut num_used_syms = 0u32;
    for c in counters.iter_mut().skip(1) {
        let count = *c;
        *c = num_used_syms;
        num_used_syms += count;
    }

    for (sym, &freq) in freqs.iter().enumerate() {
        if freq != 0 {
            let idx = freq.min((num_counters - 1) as u32) as usize;
            symout[counters[idx] as usize] = sym as u32 | (freq << NUM_SYMBOL_BITS);
            counters[idx] += 1;
        } else {
            lens[sym] = 0;
        }
    }

    // Sort the high-frequency symbols that all landed in the last counter.
    let lo = counters[num_counters - 2] as usize;
    let hi = counters[num_counters - 1] as usize;
    heap_sort(&mut symout[lo..hi]);

    num_used_syms as usize
}

// ---- build_tree ----

/// Build the stripped-down Huffman tree (non-leaf nodes only) in place.
/// `a[0..sym_count]` holds packed frequencies on input; on output the non-leaf
/// nodes hold parent-index information. Port of `build_tree`. `sym_count >= 2`.
fn build_tree(a: &mut [u32], sym_count: usize) {
    let last_idx = sym_count - 1;
    let mut i = 0usize; // next lowest-freq leaf needing a parent
    let mut b = 0usize; // next lowest-freq non-leaf needing a parent
    let mut e = 0usize; // next slot for a non-leaf

    loop {
        let new_freq;
        if i < last_idx && (b == e || (a[i + 1] & FREQ_MASK) <= (a[b] & FREQ_MASK)) {
            // Two leaves.
            new_freq = (a[i] & FREQ_MASK) + (a[i + 1] & FREQ_MASK);
            i += 2;
        } else if b + 2 <= e && (i > last_idx || (a[b + 1] & FREQ_MASK) < (a[i] & FREQ_MASK)) {
            // Two non-leaves.
            new_freq = (a[b] & FREQ_MASK) + (a[b + 1] & FREQ_MASK);
            a[b] = ((e as u32) << NUM_SYMBOL_BITS) | (a[b] & SYMBOL_MASK);
            a[b + 1] = ((e as u32) << NUM_SYMBOL_BITS) | (a[b + 1] & SYMBOL_MASK);
            b += 2;
        } else {
            // One leaf and one non-leaf.
            new_freq = (a[i] & FREQ_MASK) + (a[b] & FREQ_MASK);
            a[b] = ((e as u32) << NUM_SYMBOL_BITS) | (a[b] & SYMBOL_MASK);
            i += 1;
            b += 1;
        }
        a[e] = new_freq | (a[e] & SYMBOL_MASK);
        e += 1;
        if e >= last_idx {
            break;
        }
    }
}

// ---- compute_length_counts ----

/// Determine how many codewords have each length, honoring the length limit.
/// Port of `compute_length_counts`.
fn compute_length_counts(a: &mut [u32], root_idx: usize, len_counts: &mut [u32], max_len: usize) {
    for lc in len_counts.iter_mut().take(max_len + 1) {
        *lc = 0;
    }
    len_counts[1] = 2;

    // Root node's depth = 0.
    a[root_idx] &= SYMBOL_MASK;

    for node in (0..root_idx).rev() {
        let parent = (a[node] >> NUM_SYMBOL_BITS) as usize;
        let parent_depth = a[parent] >> NUM_SYMBOL_BITS;
        let mut depth = parent_depth as usize + 1;

        a[node] = (a[node] & SYMBOL_MASK) | ((depth as u32) << NUM_SYMBOL_BITS);

        if depth >= max_len {
            depth = max_len;
            // Move down to the largest length that already has a codeword.
            loop {
                depth -= 1;
                if len_counts[depth] != 0 {
                    break;
                }
            }
        }

        len_counts[depth] -= 1;
        len_counts[depth + 1] += 2;
    }
}

// ---- gen_codewords ----

/// Assign codeword lengths to symbols and generate canonical, bit-reversed
/// codewords. Port of `gen_codewords`.
fn gen_codewords(
    a: &mut [u32],
    lens: &mut [u8],
    len_counts: &[u32],
    max_len: usize,
    num_syms: usize,
) {
    // Assign lengths (decreasing) to symbols sorted by increasing frequency.
    let mut i = 0usize;
    let mut len = max_len;
    while len >= 1 {
        let mut count = len_counts[len];
        while count > 0 {
            let sym = (a[i] & SYMBOL_MASK) as usize;
            lens[sym] = len as u8;
            i += 1;
            count -= 1;
        }
        len -= 1;
    }

    // Lexicographically-first codeword of each length.
    let mut next_codewords = [0u32; MAX_CODEWORD_LEN + 1];
    next_codewords[0] = 0;
    next_codewords[1] = 0;
    for len in 2..=max_len {
        next_codewords[len] = (next_codewords[len - 1] + len_counts[len - 1]) << 1;
    }

    for sym in 0..num_syms {
        let l = lens[sym];
        a[sym] = reverse_codeword(next_codewords[l as usize], l);
        next_codewords[l as usize] += 1;
    }
}

// ---- deflate_make_huffman_code ----

/// Build a length-limited canonical Huffman code from symbol frequencies.
///
/// `max_len` bounds every codeword length. Port of `deflate_make_huffman_code`,
/// including the "fewer than 2 used symbols" practice-not-spec special case
/// (emit two 1-bit codewords).
pub fn make_huffman_code(num_syms: usize, max_len: u32, freqs: &[u32]) -> HuffmanCode {
    assert_eq!(freqs.len(), num_syms);
    assert!(num_syms >= 2);
    let max_len = max_len as usize;

    let mut lens = vec![0u8; num_syms];
    let mut a = vec![0u32; num_syms]; // doubles as symout, tree, and codewords

    let num_used_syms = sort_symbols(freqs, &mut lens, &mut a);

    if num_used_syms < 2 {
        let sym = if num_used_syms != 0 {
            (a[0] & SYMBOL_MASK) as usize
        } else {
            0
        };
        let nonzero_idx = if sym != 0 { sym } else { 1 };
        // Reset (sort_symbols zeroed non-used lens already, but be explicit).
        for l in lens.iter_mut() {
            *l = 0;
        }
        a[0] = 0;
        lens[0] = 1;
        a[nonzero_idx] = 1;
        lens[nonzero_idx] = 1;
        return HuffmanCode { lens, codewords: a };
    }

    build_tree(&mut a, num_used_syms);

    let mut len_counts = [0u32; MAX_CODEWORD_LEN + 2];
    compute_length_counts(&mut a, num_used_syms - 2, &mut len_counts, max_len);
    gen_codewords(&mut a, &mut lens, &len_counts, max_len, num_syms);

    HuffmanCode { lens, codewords: a }
}

// ---- dynamic-block header (precode) ----

/// Everything needed to emit a DEFLATE dynamic-block header.
pub struct DynamicHeader {
    pub num_litlen_syms: usize,
    pub num_offset_syms: usize,
    pub num_explicit_lens: usize,
    /// RLE items: low 5 bits = precode symbol, high bits = extra-bit value.
    pub items: Vec<u32>,
    /// Precode (19 symbols).
    pub precode: HuffmanCode,
}

/// Compute the precode RLE "items" and the precode symbol frequencies for a set
/// of contiguous litlen+offset codeword lengths. Port of
/// `deflate_compute_precode_items`.
fn compute_precode_items(lens: &[u8]) -> ([u32; DEFLATE_NUM_PRECODE_SYMS], Vec<u32>) {
    let mut freqs = [0u32; DEFLATE_NUM_PRECODE_SYMS];
    let mut items: Vec<u32> = Vec::new();
    let num_lens = lens.len();

    let mut run_start = 0usize;
    loop {
        let len = lens[run_start];

        // Extend the run of equal lengths.
        let mut run_end = run_start;
        loop {
            run_end += 1;
            if run_end == num_lens || len != lens[run_end] {
                break;
            }
        }

        if len == 0 {
            // Symbol 18: 11..=138 zeroes.
            while (run_end - run_start) >= 11 {
                let extra = ((run_end - run_start) - 11).min(0x7F) as u32;
                freqs[18] += 1;
                items.push(18 | (extra << 5));
                run_start += 11 + extra as usize;
            }
            // Symbol 17: 3..=10 zeroes.
            if (run_end - run_start) >= 3 {
                let extra = ((run_end - run_start) - 3).min(0x7) as u32;
                freqs[17] += 1;
                items.push(17 | (extra << 5));
                run_start += 3 + extra as usize;
            }
        } else if (run_end - run_start) >= 4 {
            // Symbol 16: repeat previous nonzero length 3..=6 times.
            freqs[len as usize] += 1;
            items.push(len as u32);
            run_start += 1;
            loop {
                let extra = ((run_end - run_start) - 3).min(0x3) as u32;
                freqs[16] += 1;
                items.push(16 | (extra << 5));
                run_start += 3 + extra as usize;
                if (run_end - run_start) < 3 {
                    break;
                }
            }
        }

        // Any remaining lengths emitted literally.
        while run_start != run_end {
            freqs[len as usize] += 1;
            items.push(len as u32);
            run_start += 1;
        }

        if run_start == num_lens {
            break;
        }
    }

    (freqs, items)
}

/// Build the dynamic-block header from the full (untrimmed) litlen and offset
/// codeword-length arrays. Port of `deflate_precompute_huffman_header`.
pub fn build_dynamic_header(litlen_lens: &[u8], offset_lens: &[u8]) -> DynamicHeader {
    // Trim trailing zero litlen lengths (keep at least 257).
    let mut num_litlen_syms = litlen_lens.len();
    while num_litlen_syms > 257 && litlen_lens[num_litlen_syms - 1] == 0 {
        num_litlen_syms -= 1;
    }
    // Trim trailing zero offset lengths (keep at least 1).
    let mut num_offset_syms = offset_lens.len();
    while num_offset_syms > 1 && offset_lens[num_offset_syms - 1] == 0 {
        num_offset_syms -= 1;
    }

    // Contiguous litlen+offset lengths (replaces libdeflate's in-place memmove).
    let mut combined: Vec<u8> = Vec::with_capacity(num_litlen_syms + num_offset_syms);
    combined.extend_from_slice(&litlen_lens[..num_litlen_syms]);
    combined.extend_from_slice(&offset_lens[..num_offset_syms]);

    let (precode_freqs, items) = compute_precode_items(&combined);

    let precode = make_huffman_code(
        DEFLATE_NUM_PRECODE_SYMS,
        MAX_PRE_CODEWORD_LEN,
        &precode_freqs,
    );

    // Count how many precode lengths must actually be written (>= 4).
    let mut num_explicit_lens = DEFLATE_NUM_PRECODE_SYMS;
    while num_explicit_lens > 4
        && precode.lens[PRECODE_LENS_PERMUTATION[num_explicit_lens - 1] as usize] == 0
    {
        num_explicit_lens -= 1;
    }

    DynamicHeader {
        num_litlen_syms,
        num_offset_syms,
        num_explicit_lens,
        items,
        precode,
    }
}

impl DynamicHeader {
    /// Exact bit cost of the header body (everything after BFINAL+BTYPE):
    /// HLIT/HDIST/HCLEN + precode lengths + the RLE-encoded litlen/offset
    /// lengths. Used by the stored-vs-dynamic decision.
    pub fn header_bits(&self) -> u64 {
        let mut bits = 5 + 5 + 4 + 3 * self.num_explicit_lens as u64;
        for &item in &self.items {
            let sym = (item & 0x1F) as usize;
            bits += self.precode.lens[sym] as u64 + PRECODE_EXTRA_BITS[sym] as u64;
        }
        bits
    }

    /// Emit the header body. The caller must already have written the 3-bit
    /// BFINAL + BTYPE(dynamic) prefix.
    pub fn emit(&self, bw: &mut BitWriter) {
        bw.add_bits((self.num_litlen_syms - 257) as u64, 5);
        bw.add_bits((self.num_offset_syms - 1) as u64, 5);
        bw.add_bits((self.num_explicit_lens - 4) as u64, 4);

        // Precode codeword lengths, in permutation order.
        for &sym in PRECODE_LENS_PERMUTATION.iter().take(self.num_explicit_lens) {
            bw.add_bits(self.precode.lens[sym as usize] as u64, 3);
        }

        // RLE-encoded litlen + offset codeword lengths.
        for &item in &self.items {
            let sym = (item & 0x1F) as usize;
            bw.add_bits(
                self.precode.codewords[sym] as u64,
                self.precode.lens[sym] as u32,
            );
            bw.add_bits((item >> 5) as u64, PRECODE_EXTRA_BITS[sym] as u32);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A canonical prefix code must satisfy the Kraft inequality: sum of
    /// 2^-len over used symbols <= 1, and be prefix-free (verified by decoding).
    fn assert_valid_code(code: &HuffmanCode, max_len: u32) {
        let mut kraft = 0f64;
        for &l in &code.lens {
            assert!(
                l as u32 <= max_len,
                "codeword length {l} exceeds max {max_len}"
            );
            if l > 0 {
                kraft += 2f64.powi(-(l as i32));
            }
        }
        assert!(kraft <= 1.0 + 1e-9, "Kraft sum {kraft} > 1");

        // Prefix-free check: insert every (reversed) codeword into a set keyed
        // by the MSB-first bit string and ensure no codeword is a prefix of
        // another. The stream writes bit-reversed codewords LSB-first, i.e. the
        // decoder reads them MSB-first as `codeword` un-reversed. Reconstruct
        // the forward codeword bits for prefix testing.
        let mut seen: Vec<(u32, u8)> = Vec::new();
        for (sym, (&l, &cw)) in code.lens.iter().zip(code.codewords.iter()).enumerate() {
            if l == 0 {
                continue;
            }
            // `cw` is the bit-reversed codeword; reverse it back to forward bits.
            let forward = reverse_low_bits(cw, l);
            for &(other, ol) in &seen {
                let (short, sl, long, _ll) = if l <= ol {
                    (forward, l, other, ol)
                } else {
                    (other, ol, forward, l)
                };
                // Is `short` a prefix of `long`?
                let long_top = long >> (_ll - sl);
                assert_ne!(long_top, short, "symbol {sym}: codeword collides/prefixes");
            }
            seen.push((forward, l));
        }
    }

    fn reverse_low_bits(v: u32, len: u8) -> u32 {
        let mut r = 0;
        for i in 0..len {
            if (v >> i) & 1 != 0 {
                r |= 1 << (len - 1 - i);
            }
        }
        r
    }

    #[test]
    fn uniform_frequencies_balanced() {
        let freqs = [1u32; 8];
        let code = make_huffman_code(8, 15, &freqs);
        // 8 uniform symbols => all length 3.
        for &l in &code.lens {
            assert_eq!(l, 3);
        }
        assert_valid_code(&code, 15);
    }

    #[test]
    fn skewed_frequencies_valid_and_limited() {
        let mut freqs = vec![0u32; 288];
        // Heavy skew that would drive a naive Huffman code past 14 bits.
        let mut f = 1u32;
        for i in 0..30 {
            freqs[i] = f;
            f = f.saturating_add(f); // Fibonacci-ish blowup -> long codewords
        }
        freqs[256] = 1;
        let code = make_huffman_code(288, 14, &freqs);
        assert_valid_code(&code, 14);
    }

    #[test]
    fn single_used_symbol_gets_two_codewords() {
        let mut freqs = vec![0u32; 32];
        freqs[5] = 100;
        let code = make_huffman_code(32, 15, &freqs);
        assert_eq!(code.lens[0], 1);
        assert_eq!(code.lens[5], 1);
        // Exactly two length-1 codewords.
        assert_eq!(code.lens.iter().filter(|&&l| l == 1).count(), 2);
        assert_valid_code(&code, 15);
    }

    #[test]
    fn no_used_symbols_gets_two_codewords() {
        let freqs = vec![0u32; 32];
        let code = make_huffman_code(32, 15, &freqs);
        assert_eq!(code.lens[0], 1);
        assert_eq!(code.lens[1], 1);
        assert_valid_code(&code, 15);
    }

    #[test]
    fn static_litlen_code_matches_rfc_lengths() {
        // static_litlen_freqs => the RFC fixed code: 0..144=8, 144..256=9,
        // 256..280=7, 280..288=8.
        let freqs = super::super::tables::static_litlen_freqs();
        let code = make_huffman_code(288, 15, &freqs);
        for i in 0..144 {
            assert_eq!(code.lens[i], 8, "sym {i}");
        }
        for i in 144..256 {
            assert_eq!(code.lens[i], 9, "sym {i}");
        }
        for i in 256..280 {
            assert_eq!(code.lens[i], 7, "sym {i}");
        }
        for i in 280..288 {
            assert_eq!(code.lens[i], 8, "sym {i}");
        }
        assert_valid_code(&code, 15);
    }

    #[test]
    fn precode_items_roundtrip_lengths() {
        // A lengths array with runs of zeros and repeats; reconstruct it by
        // interpreting the items and confirm we get the original back.
        let lens: Vec<u8> = vec![
            5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 7, 7, 7, 7, 7, 7,
        ];
        let (_freqs, items) = compute_precode_items(&lens);
        let mut out: Vec<u8> = Vec::new();
        let mut prev = 0u8;
        for &item in &items {
            let sym = (item & 0x1F) as u8;
            let extra = item >> 5;
            match sym {
                16 => {
                    let n = 3 + extra;
                    out.resize(out.len() + n as usize, prev);
                }
                17 => {
                    let n = 3 + extra;
                    out.resize(out.len() + n as usize, 0);
                }
                18 => {
                    let n = 11 + extra;
                    out.resize(out.len() + n as usize, 0);
                }
                l => {
                    out.push(l);
                    prev = l;
                }
            }
        }
        assert_eq!(out, lens);
    }

    #[test]
    fn reverse_codeword_known() {
        // 0b001 (3 bits) reversed => 0b100 = 4.
        assert_eq!(reverse_codeword(0b001, 3), 0b100);
        // 0b1011 (4 bits) reversed => 0b1101 = 13.
        assert_eq!(reverse_codeword(0b1011, 4), 0b1101);
        assert_eq!(reverse_codeword(0, 5), 0);
    }
}
