//! AOT codegen for top-N Huffman fingerprints (plan §3.1 AOT half).
//!
//! Emits `$OUT_DIR/aot_fingerprints.rs` containing pre-built CHD
//! decode tables for common (litlen, dist) code-length tuples. The
//! runtime checks the parsed block header against the AOT table; on
//! hit, uses the pre-built CHD; on miss, falls back to the runtime
//! `ChdTable::build`.
//!
//! v1 ships ONE pre-built fingerprint (RFC 1951 fixed Huffman).
//! v2 walks a representative corpus to discover the top-N actual
//! fingerprints and bakes them all in. v3 emits dynasm asm per
//! fingerprint per plan §3.1 (months of work).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("aot_fingerprints.rs");

    // Fixed-Huffman fingerprint per RFC 1951 §3.2.6.
    // 288 litlen code lengths + 30 dist code lengths (all 5).
    let mut litlen = [0u8; 288];
    for entry in litlen.iter_mut().take(144) {
        *entry = 8;
    }
    for entry in litlen.iter_mut().take(256).skip(144) {
        *entry = 9;
    }
    for entry in litlen.iter_mut().take(280).skip(256) {
        *entry = 7;
    }
    for entry in litlen.iter_mut().take(288).skip(280) {
        *entry = 8;
    }
    let dist = [5u8; 30];

    // 64-bit fingerprint hash of (litlen | dist) code lengths.
    let fingerprint = fingerprint_hash(&litlen, &dist);

    // Emit a Rust source file with the fingerprint + a function that
    // returns the canonical code-length arrays. Runtime can compare
    // its parsed fingerprint against the AOT'd one and use the
    // cached CHD instead of building at runtime.
    let mut emit = String::new();
    emit.push_str(
        "// Generated by build.rs. Do not edit.\n\
         //\n\
         // AOT-built Huffman fingerprints — pre-compiled at crate build\n\
         // time so the runtime can skip the per-block CHD construction\n\
         // for the most common code-length patterns.\n\n",
    );
    emit.push_str("/// 64-bit hash of (litlen_code_lengths | dist_code_lengths).\n");
    emit.push_str("/// Stable across runs; matches `fingerprint_hash` in lib.rs.\n");
    emit.push_str("pub type Fingerprint = u64;\n\n");

    emit.push_str("/// Pre-built fingerprints. v1 ships only the RFC 1951 fixed-Huffman\n");
    emit.push_str("/// fingerprint; v2 walks silesia + linux-source for the top-N.\n");
    emit.push_str("pub const AOT_FINGERPRINTS: &[(Fingerprint, &str)] = &[\n");
    emit.push_str(&format!(
        "    ({:#018x}, \"fixed-huffman-rfc1951\"),\n",
        fingerprint
    ));
    emit.push_str("];\n\n");

    emit.push_str("/// Number of AOT'd fingerprints. Bench harness reports this to\n");
    emit.push_str("/// confirm the build emitted the expected count.\n");
    emit.push_str(&format!(
        "pub const AOT_FINGERPRINT_COUNT: usize = {};\n",
        1
    ));

    fs::write(&dest, emit).expect("write aot_fingerprints.rs");

    // Cargo cache key: only re-run when build.rs itself changes.
    println!("cargo:rerun-if-changed=build.rs");
}

/// Stable 64-bit hash of (litlen | dist) code lengths. Matches the
/// runtime implementation in `lib.rs::fingerprint_hash`. We keep them
/// in lockstep by re-emitting the same Murmur-style scrambler here.
fn fingerprint_hash(litlen: &[u8; 288], dist: &[u8; 30]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in litlen.iter() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01b3);
    }
    for &b in dist.iter() {
        h ^= b as u64;
        h = h.wrapping_mul(0x100_0000_01b3);
    }
    h
}
