//! Length-limited canonical Huffman code construction — the APPROXIMATE,
//! fast builder used by every hot level (L2-12) and near-optimal.
//!
//! Port of libdeflate `vendor/libdeflate/lib/deflate_compress.c`:
//! `sort_symbols` / `build_tree` / `compute_length_counts` / `gen_codewords` /
//! `deflate_make_huffman_code` (~:846-1396, the counting-sort + stripped-tree +
//! APPROXIMATE length limiter) and `reverse_codeword` (~:1104-1152).
//!
//! The EXACT (katajainen/package-merge) builder lives in the sibling
//! [`super::optimal`] module; the dynamic-block header builder+emitter that
//! consumes this module's [`HuffmanCode`] output lives in [`super::header`].
//! See `docs/compressor-architecture.md` §2 for the full `huffman/` map.
//!
//! Correctness contract: the produced code is canonical and length-limited, so
//! every nonzero-frequency symbol gets a decodable codeword and the Kraft sum
//! is <= 1.

use super::HuffmanCode;

const NUM_SYMBOL_BITS: u32 = 10;
const SYMBOL_MASK: u32 = (1 << NUM_SYMBOL_BITS) - 1;
const FREQ_MASK: u32 = !SYMBOL_MASK;
/// Largest codeword length any DEFLATE code can use (offset code, 15 bits).
const MAX_CODEWORD_LEN: usize = 15;

// ---- bit reversal (reverse_codeword) ----

/// `bitreverse_tab[]` from libdeflate (generated by gen_bitreverse_tab.py).
const BITREVERSE_TAB: [u8; 256] = {
    let mut t = [0u8; 256];
    let mut i = 0usize;
    while i < 256 {
        let mut v = 0u8;
        let mut b = 0u32;
        while b < 8 {
            if (i >> b) & 1 != 0 {
                v |= 1 << (7 - b);
            }
            b += 1;
        }
        t[i] = v;
        i += 1;
    }
    t
};

/// Reverse the low `len` bits of `codeword` (DEFLATE uses bit-reversed
/// codewords). `len <= 16`.
#[inline]
fn reverse_codeword(codeword: u32, len: u8) -> u32 {
    // SAFETY: `codeword & 0xff` and `(codeword >> 8) & 0xff` are always
    // `0..=255` by construction of the mask, in bounds for the 256-entry
    // `BITREVERSE_TAB` regardless of `codeword`'s value.
    let cw = unsafe {
        (*BITREVERSE_TAB.get_unchecked((codeword & 0xff) as usize) as u32) << 8
            | (*BITREVERSE_TAB.get_unchecked(((codeword >> 8) & 0xff) as usize) as u32)
    };
    cw >> (16 - len as u32)
}

// ---- heap sort over packed (freq<<10 | sym) entries ----

#[inline]
fn heapify_subtree(a: &mut [u32], length: usize, subtree_idx: usize) {
    // 1-based indices, so a[idx] maps to slice a[idx-1].
    //
    // SAFETY (whole body): caller passes `1 <= subtree_idx <= length <=
    // a.len()` (heapify_array/heap_sort's call sites). The loop only enters
    // a body when `child_idx <= length`, so every `child_idx - 1` /
    // `parent_idx - 1` index used below is `< length <= a.len()` — the same
    // 1-based sift-down invariant libdeflate's C `heapify_subtree` relies on
    // with raw pointers (no bounds checking there either).
    debug_assert!(subtree_idx >= 1 && subtree_idx <= length && length <= a.len());
    let v = unsafe { *a.get_unchecked(subtree_idx - 1) };
    let mut parent_idx = subtree_idx;
    loop {
        let mut child_idx = parent_idx * 2;
        if child_idx > length {
            break;
        }
        if child_idx < length
            && unsafe { *a.get_unchecked(child_idx) > *a.get_unchecked(child_idx - 1) }
        {
            child_idx += 1;
        }
        if v >= unsafe { *a.get_unchecked(child_idx - 1) } {
            break;
        }
        unsafe {
            *a.get_unchecked_mut(parent_idx - 1) = *a.get_unchecked(child_idx - 1);
        }
        parent_idx = child_idx;
    }
    unsafe {
        *a.get_unchecked_mut(parent_idx - 1) = v;
    }
}

fn heapify_array(a: &mut [u32], length: usize) {
    let mut subtree_idx = length / 2;
    while subtree_idx >= 1 {
        heapify_subtree(a, length, subtree_idx);
        subtree_idx -= 1;
    }
}

/// Heapsort `a` in place (ascending). Port of `heap_sort`.
fn heap_sort(a: &mut [u32]) {
    let mut length = a.len();
    if length < 2 {
        return;
    }
    heapify_array(a, length);
    while length >= 2 {
        a.swap(length - 1, 0);
        length -= 1;
        heapify_subtree(a, length, 1);
    }
}

// ---- sort_symbols ----

/// Count-sort symbols by frequency (secondary: symbol value), packing
/// `sym | (freq << 10)` into `symout`. Zero-frequency symbols get `lens[sym]=0`.
/// Returns the number of used (nonzero-frequency) symbols.
fn sort_symbols(freqs: &[u32], lens: &mut [u8], symout: &mut [u32]) -> usize {
    let num_syms = freqs.len();
    let num_counters = num_syms;
    let mut counters = vec![0u32; num_counters];

    // SAFETY (whole body): `idx = f.min(num_counters - 1)` is clamped to
    // `< num_counters == counters.len()` on every use below, and
    // `counters[idx]` is a running count that counting-sort's own postcondition
    // keeps `< num_used_syms <= num_syms == symout.len()`, mirroring
    // libdeflate's C `sort_symbols` (same counting-sort over raw arrays, no
    // bounds checks there either). `num_counters >= 2` is guaranteed by
    // `make_huffman_code`'s `assert!(num_syms >= 2)`.
    for &f in freqs.iter() {
        let idx = f.min((num_counters - 1) as u32) as usize;
        unsafe {
            *counters.get_unchecked_mut(idx) += 1;
        }
    }

    // Make counters cumulative (ignoring counter 0 = zero-frequency symbols).
    let mut num_used_syms = 0u32;
    for c in counters.iter_mut().skip(1) {
        let count = *c;
        *c = num_used_syms;
        num_used_syms += count;
    }

    for (sym, &freq) in freqs.iter().enumerate() {
        if freq != 0 {
            let idx = freq.min((num_counters - 1) as u32) as usize;
            unsafe {
                let slot = counters.get_unchecked_mut(idx);
                *symout.get_unchecked_mut(*slot as usize) = sym as u32 | (freq << NUM_SYMBOL_BITS);
                *slot += 1;
            }
        } else {
            // SAFETY: `sym` comes from `freqs.iter().enumerate()`, and `lens`
            // has the same length as `freqs` (`num_syms`, asserted by the
            // caller), so `sym < lens.len()`.
            unsafe {
                *lens.get_unchecked_mut(sym) = 0;
            }
        }
    }

    // Sort the high-frequency symbols that all landed in the last counter.
    let lo = unsafe { *counters.get_unchecked(num_counters - 2) as usize };
    let hi = unsafe { *counters.get_unchecked(num_counters - 1) as usize };
    heap_sort(&mut symout[lo..hi]);

    num_used_syms as usize
}

// ---- build_tree ----

/// Build the stripped-down Huffman tree (non-leaf nodes only) in place.
/// `a[0..sym_count]` holds packed frequencies on input; on output the non-leaf
/// nodes hold parent-index information. Port of `build_tree`. `sym_count >= 2`.
fn build_tree(a: &mut [u32], sym_count: usize) {
    let last_idx = sym_count - 1;
    let mut i = 0usize; // next lowest-freq leaf needing a parent
    let mut b = 0usize; // next lowest-freq non-leaf needing a parent
    let mut e = 0usize; // next slot for a non-leaf

    debug_assert!(sym_count >= 2 && sym_count <= a.len());

    // SAFETY (whole body): this is a direct port of libdeflate's C
    // `build_tree`, which runs the identical index arithmetic over a raw
    // `uint32_t[]` with no bounds checking. Its loop invariant is `i <=
    // sym_count`, `b <= e`, and `e < last_idx` (the loop's own break
    // condition) throughout, so every `a[i]`, `a[i+1]`, `a[b]`, `a[b+1]`, and
    // `a[e]` access below stays `< sym_count <= a.len()`:
    //   - the two-leaves arm only runs when `i < last_idx`, so `i+1 <=
    //     last_idx < sym_count`;
    //   - the two-non-leaves arm only runs when `b + 2 <= e < last_idx <
    //     sym_count`, so `b+1 < sym_count`;
    //   - the fallback arm requires `i <= last_idx < sym_count` (the two-
    //     leaves guard having failed) and `b < e < sym_count`;
    //   - `e` is checked `< sym_count` by the loop's break test using
    //     `last_idx = sym_count - 1` before every write to `a[e]`.
    loop {
        let new_freq;
        unsafe {
            if i < last_idx
                && (b == e
                    || (*a.get_unchecked(i + 1) & FREQ_MASK) <= (*a.get_unchecked(b) & FREQ_MASK))
            {
                // Two leaves.
                new_freq =
                    (*a.get_unchecked(i) & FREQ_MASK) + (*a.get_unchecked(i + 1) & FREQ_MASK);
                i += 2;
            } else if b + 2 <= e
                && (i > last_idx
                    || (*a.get_unchecked(b + 1) & FREQ_MASK) < (*a.get_unchecked(i) & FREQ_MASK))
            {
                // Two non-leaves.
                new_freq =
                    (*a.get_unchecked(b) & FREQ_MASK) + (*a.get_unchecked(b + 1) & FREQ_MASK);
                *a.get_unchecked_mut(b) =
                    ((e as u32) << NUM_SYMBOL_BITS) | (*a.get_unchecked(b) & SYMBOL_MASK);
                *a.get_unchecked_mut(b + 1) =
                    ((e as u32) << NUM_SYMBOL_BITS) | (*a.get_unchecked(b + 1) & SYMBOL_MASK);
                b += 2;
            } else {
                // One leaf and one non-leaf.
                new_freq = (*a.get_unchecked(i) & FREQ_MASK) + (*a.get_unchecked(b) & FREQ_MASK);
                *a.get_unchecked_mut(b) =
                    ((e as u32) << NUM_SYMBOL_BITS) | (*a.get_unchecked(b) & SYMBOL_MASK);
                i += 1;
                b += 1;
            }
            *a.get_unchecked_mut(e) = new_freq | (*a.get_unchecked(e) & SYMBOL_MASK);
        }
        e += 1;
        if e >= last_idx {
            break;
        }
    }
}

// ---- compute_length_counts ----

/// Determine how many codewords have each length, honoring the length limit.
/// Port of `compute_length_counts`.
fn compute_length_counts(a: &mut [u32], root_idx: usize, len_counts: &mut [u32], max_len: usize) {
    // `len_counts` is always the caller's `[0u32; MAX_CODEWORD_LEN + 2]`
    // (17 entries) and `max_len <= MAX_CODEWORD_LEN` (15), so indices
    // `0..=max_len` and `depth`/`depth+1` (both `<= max_len + 1 <= 16`) stay
    // `< len_counts.len()`.
    debug_assert!(max_len + 1 < len_counts.len());
    for lc in len_counts.iter_mut().take(max_len + 1) {
        *lc = 0;
    }
    len_counts[1] = 2;

    // Root node's depth = 0. `root_idx < a.len()` by construction (it is
    // `num_used_syms - 2`, a valid non-leaf slot build_tree just wrote).
    debug_assert!(root_idx < a.len());
    unsafe {
        *a.get_unchecked_mut(root_idx) &= SYMBOL_MASK;
    }

    // SAFETY (loop body): this is a direct port of libdeflate's C
    // `compute_length_counts`, which walks the same tree with no bounds
    // checking. `node` ranges `0..root_idx < a.len()`. `parent` is the
    // parent-index field build_tree wrote into a non-leaf slot strictly
    // between `node+1` and `root_idx` inclusive, so `parent <= root_idx <
    // a.len()`. `depth`/`depth+1` are clamped to `<= max_len + 1 <
    // len_counts.len()` by the `depth >= max_len` branch below before every
    // `len_counts` access.
    for node in (0..root_idx).rev() {
        let parent = unsafe { (*a.get_unchecked(node) >> NUM_SYMBOL_BITS) as usize };
        debug_assert!(parent <= root_idx);
        let parent_depth = unsafe { *a.get_unchecked(parent) >> NUM_SYMBOL_BITS };
        let mut depth = parent_depth as usize + 1;

        unsafe {
            *a.get_unchecked_mut(node) =
                (*a.get_unchecked(node) & SYMBOL_MASK) | ((depth as u32) << NUM_SYMBOL_BITS);
        }

        if depth >= max_len {
            depth = max_len;
            // Move down to the largest length that already has a codeword.
            loop {
                depth -= 1;
                if unsafe { *len_counts.get_unchecked(depth) != 0 } {
                    break;
                }
            }
        }

        unsafe {
            *len_counts.get_unchecked_mut(depth) -= 1;
            *len_counts.get_unchecked_mut(depth + 1) += 2;
        }
    }
}

// ---- gen_codewords ----

/// Assign codeword lengths to symbols and generate canonical, bit-reversed
/// codewords. Port of `gen_codewords`.
fn gen_codewords(
    a: &mut [u32],
    lens: &mut [u8],
    len_counts: &[u32],
    max_len: usize,
    num_syms: usize,
) {
    debug_assert!(max_len < len_counts.len() && max_len < MAX_CODEWORD_LEN + 1);
    // Assign lengths (decreasing) to symbols sorted by increasing frequency.
    //
    // SAFETY: `len` only ranges `1..=max_len < len_counts.len()`. `i` walks
    // 0..num_used_syms as `count` sums to `num_used_syms` over the loop (the
    // codeword-length-count invariant `compute_length_counts` established),
    // and `num_used_syms <= num_syms == a.len() == lens.len()`, so `a[i]`
    // stays in bounds and the derived `sym = a[i] & SYMBOL_MASK` is an
    // original symbol index `< num_syms == lens.len()` (packed by
    // `sort_symbols`).
    let mut i = 0usize;
    let mut len = max_len;
    while len >= 1 {
        let mut count = unsafe { *len_counts.get_unchecked(len) };
        while count > 0 {
            let sym = unsafe { (*a.get_unchecked(i) & SYMBOL_MASK) as usize };
            unsafe {
                *lens.get_unchecked_mut(sym) = len as u8;
            }
            i += 1;
            count -= 1;
        }
        len -= 1;
    }

    // Lexicographically-first codeword of each length.
    let mut next_codewords = [0u32; MAX_CODEWORD_LEN + 1];
    next_codewords[0] = 0;
    next_codewords[1] = 0;
    // SAFETY: `len` ranges `2..=max_len < MAX_CODEWORD_LEN + 1 ==
    // next_codewords.len()`, and `len_counts.len() > max_len >= len - 1`.
    for len in 2..=max_len {
        next_codewords[len] =
            (next_codewords[len - 1] + unsafe { *len_counts.get_unchecked(len - 1) }) << 1;
    }

    // SAFETY: `sym` ranges `0..num_syms == a.len() == lens.len()`. `l =
    // lens[sym]` was assigned above from the `1..=max_len` loop (or left 0
    // for an unused symbol only when `l==0` can't reach this table — every
    // used symbol got a length `<= max_len`), so `l as usize <= max_len <
    // next_codewords.len()`.
    for sym in 0..num_syms {
        let l = unsafe { *lens.get_unchecked(sym) };
        let next = unsafe { next_codewords.get_unchecked_mut(l as usize) };
        unsafe {
            *a.get_unchecked_mut(sym) = reverse_codeword(*next, l);
        }
        *next += 1;
    }
}

// ---- deflate_make_huffman_code ----

/// Build a length-limited canonical Huffman code from symbol frequencies.
///
/// `max_len` bounds every codeword length. Port of `deflate_make_huffman_code`,
/// including the "fewer than 2 used symbols" practice-not-spec special case
/// (emit two 1-bit codewords).
pub fn make_huffman_code(num_syms: usize, max_len: u32, freqs: &[u32]) -> HuffmanCode {
    assert_eq!(freqs.len(), num_syms);
    assert!(num_syms >= 2);
    let max_len = max_len as usize;

    let mut lens = vec![0u8; num_syms];
    let mut a = vec![0u32; num_syms]; // doubles as symout, tree, and codewords

    let num_used_syms = sort_symbols(freqs, &mut lens, &mut a);

    if num_used_syms < 2 {
        let sym = if num_used_syms != 0 {
            (a[0] & SYMBOL_MASK) as usize
        } else {
            0
        };
        let nonzero_idx = if sym != 0 { sym } else { 1 };
        // Reset (sort_symbols zeroed non-used lens already, but be explicit).
        for l in lens.iter_mut() {
            *l = 0;
        }
        a[0] = 0;
        lens[0] = 1;
        a[nonzero_idx] = 1;
        lens[nonzero_idx] = 1;
        return HuffmanCode { lens, codewords: a };
    }

    build_tree(&mut a, num_used_syms);

    let mut len_counts = [0u32; MAX_CODEWORD_LEN + 2];
    compute_length_counts(&mut a, num_used_syms - 2, &mut len_counts, max_len);
    gen_codewords(&mut a, &mut lens, &len_counts, max_len, num_syms);

    HuffmanCode { lens, codewords: a }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A canonical prefix code must satisfy the Kraft inequality: sum of
    /// 2^-len over used symbols <= 1, and be prefix-free (verified by decoding).
    fn assert_valid_code(code: &HuffmanCode, max_len: u32) {
        let mut kraft = 0f64;
        for &l in &code.lens {
            assert!(
                l as u32 <= max_len,
                "codeword length {l} exceeds max {max_len}"
            );
            if l > 0 {
                kraft += 2f64.powi(-(l as i32));
            }
        }
        assert!(kraft <= 1.0 + 1e-9, "Kraft sum {kraft} > 1");

        // Prefix-free check: insert every (reversed) codeword into a set keyed
        // by the MSB-first bit string and ensure no codeword is a prefix of
        // another. The stream writes bit-reversed codewords LSB-first, i.e. the
        // decoder reads them MSB-first as `codeword` un-reversed. Reconstruct
        // the forward codeword bits for prefix testing.
        let mut seen: Vec<(u32, u8)> = Vec::new();
        for (sym, (&l, &cw)) in code.lens.iter().zip(code.codewords.iter()).enumerate() {
            if l == 0 {
                continue;
            }
            // `cw` is the bit-reversed codeword; reverse it back to forward bits.
            let forward = reverse_low_bits(cw, l);
            for &(other, ol) in &seen {
                let (short, sl, long, _ll) = if l <= ol {
                    (forward, l, other, ol)
                } else {
                    (other, ol, forward, l)
                };
                // Is `short` a prefix of `long`?
                let long_top = long >> (_ll - sl);
                assert_ne!(long_top, short, "symbol {sym}: codeword collides/prefixes");
            }
            seen.push((forward, l));
        }
    }

    fn reverse_low_bits(v: u32, len: u8) -> u32 {
        let mut r = 0;
        for i in 0..len {
            if (v >> i) & 1 != 0 {
                r |= 1 << (len - 1 - i);
            }
        }
        r
    }

    #[test]
    fn uniform_frequencies_balanced() {
        let freqs = [1u32; 8];
        let code = make_huffman_code(8, 15, &freqs);
        // 8 uniform symbols => all length 3.
        for &l in &code.lens {
            assert_eq!(l, 3);
        }
        assert_valid_code(&code, 15);
    }

    #[test]
    fn skewed_frequencies_valid_and_limited() {
        let mut freqs = vec![0u32; 288];
        // Heavy skew that would drive a naive Huffman code past 14 bits.
        let mut f = 1u32;
        for i in 0..30 {
            freqs[i] = f;
            f = f.saturating_add(f); // Fibonacci-ish blowup -> long codewords
        }
        freqs[256] = 1;
        let code = make_huffman_code(288, 14, &freqs);
        assert_valid_code(&code, 14);
    }

    #[test]
    fn single_used_symbol_gets_two_codewords() {
        let mut freqs = vec![0u32; 32];
        freqs[5] = 100;
        let code = make_huffman_code(32, 15, &freqs);
        assert_eq!(code.lens[0], 1);
        assert_eq!(code.lens[5], 1);
        // Exactly two length-1 codewords.
        assert_eq!(code.lens.iter().filter(|&&l| l == 1).count(), 2);
        assert_valid_code(&code, 15);
    }

    #[test]
    fn no_used_symbols_gets_two_codewords() {
        let freqs = vec![0u32; 32];
        let code = make_huffman_code(32, 15, &freqs);
        assert_eq!(code.lens[0], 1);
        assert_eq!(code.lens[1], 1);
        assert_valid_code(&code, 15);
    }

    #[test]
    fn static_litlen_code_matches_rfc_lengths() {
        // static_litlen_freqs => the RFC fixed code: 0..144=8, 144..256=9,
        // 256..280=7, 280..288=8.
        let freqs = crate::compress::deflate::tables::static_litlen_freqs();
        let code = make_huffman_code(288, 15, &freqs);
        for i in 0..144 {
            assert_eq!(code.lens[i], 8, "sym {i}");
        }
        for i in 144..256 {
            assert_eq!(code.lens[i], 9, "sym {i}");
        }
        for i in 256..280 {
            assert_eq!(code.lens[i], 7, "sym {i}");
        }
        for i in 280..288 {
            assert_eq!(code.lens[i], 8, "sym {i}");
        }
        assert_valid_code(&code, 15);
    }

    #[test]
    fn reverse_codeword_known() {
        // 0b001 (3 bits) reversed => 0b100 = 4.
        assert_eq!(reverse_codeword(0b001, 3), 0b100);
        // 0b1011 (4 bits) reversed => 0b1101 = 13.
        assert_eq!(reverse_codeword(0b1011, 4), 0b1101);
        assert_eq!(reverse_codeword(0, 5), 0);
    }
}
