//! C: `vendor/libdeflate/lib/deflate_compress.c:237-320` — the static lookup
//! tables, plus `deflate_get_offset_slot` (:1455) which is the only function that
//! reads `deflate_offset_slot` directly.
//!
//! These are RFC 1951 wire-format tables, not tunables: `deflate_length_slot_base`,
//! `deflate_extra_length_bits`, `deflate_offset_slot_base` and
//! `deflate_extra_offset_bits` are transcribed from the standard, and the two
//! reverse maps (`deflate_length_slot`, `deflate_offset_slot`) are derived from
//! them. The tests at the bottom DERIVE both reverse maps from the forward ones and
//! compare — a transcription typo in 258 or 256 entries is exactly the kind of error
//! that survives a code read and then costs a corrupt stream.

use super::{DEFLATE_MAX_MATCH_LEN, DEFLATE_MAX_MATCH_OFFSET, DEFLATE_NUM_PRECODE_SYMS};

/// Table: length slot => length slot base value. C: `:238`
pub(crate) const DEFLATE_LENGTH_SLOT_BASE: [u32; 29] = [
    3, 4, 5, 6, 7, 8, 9, 10, //
    11, 13, 15, 17, 19, 23, 27, 31, //
    35, 43, 51, 59, 67, 83, 99, 115, //
    131, 163, 195, 227, 258,
];

/// Table: length slot => number of extra length bits. C: `:246`
pub(crate) const DEFLATE_EXTRA_LENGTH_BITS: [u8; 29] = [
    0, 0, 0, 0, 0, 0, 0, 0, //
    1, 1, 1, 1, 2, 2, 2, 2, //
    3, 3, 3, 3, 4, 4, 4, 4, //
    5, 5, 5, 5, 0,
];

/// Table: offset slot => offset slot base value. C: `:254`
pub(crate) const DEFLATE_OFFSET_SLOT_BASE: [u32; 30] = [
    1, 2, 3, 4, 5, 7, 9, 13, //
    17, 25, 33, 49, 65, 97, 129, 193, //
    257, 385, 513, 769, 1025, 1537, 2049, 3073, //
    4097, 6145, 8193, 12289, 16385, 24577,
];

/// Table: offset slot => number of extra offset bits. C: `:262`
pub(crate) const DEFLATE_EXTRA_OFFSET_BITS: [u8; 30] = [
    0, 0, 0, 0, 1, 1, 2, 2, //
    3, 3, 4, 4, 5, 5, 6, 6, //
    7, 7, 8, 8, 9, 9, 10, 10, //
    11, 11, 12, 12, 13, 13,
];

/// Table: length => length slot. C: `:270`
#[rustfmt::skip]
pub(crate) const DEFLATE_LENGTH_SLOT: [u8; DEFLATE_MAX_MATCH_LEN as usize + 1] = [
    0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 12,
    12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, 16, 16,
    16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18,
    18, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20,
    20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,
    21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
    22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
    23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,
    24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
    25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
    26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
    27, 27, 28,
];

/// Table: `offset - 1 => offset_slot` for offset <= 256. C: `:292`
///
/// (The C notes this was generated by `scripts/gen_offset_slot_map.py`.)
#[rustfmt::skip]
pub(crate) const DEFLATE_OFFSET_SLOT: [u8; 256] = [
    0, 1, 2, 3, 4, 4, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7,
    8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9,
    10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
    15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
];

/// The order in which precode codeword lengths are stored. C: `:311`
pub(crate) const DEFLATE_PRECODE_LENS_PERMUTATION: [u8; DEFLATE_NUM_PRECODE_SYMS] = [
    16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15,
];

/// Table: precode symbol => number of extra bits. C: `:316`
pub(crate) const DEFLATE_EXTRA_PRECODE_BITS: [u8; DEFLATE_NUM_PRECODE_SYMS] =
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 7];

/// C: `deflate_get_offset_slot(u32 offset)` (:1455)
///
/// Return the offset slot for the given match offset, using the small map.
///
/// 1 <= offset <= 32768 here. For 1 <= offset <= 256,
/// `deflate_offset_slot[offset - 1]` gives the slot.
///
/// For 257 <= offset <= 32768, we take advantage of the fact that 257 is the
/// beginning of slot 16, and each slot [16..30) is exactly `1 << 7 == 128` times
/// larger than each slot [2..16) (since the number of extra bits increases by 1
/// every 2 slots). Thus, the slot is:
///
/// ```text
///     deflate_offset_slot[2 + ((offset - 257) >> 7)] + (16 - 2)
///  == deflate_offset_slot[((offset - 1) >> 7)] + 14
/// ```
///
/// Define `n = (offset <= 256) ? 0 : 7`. Then any offset is handled by:
///
/// ```text
///     deflate_offset_slot[(offset - 1) >> n] + (n << 1)
/// ```
///
/// For better performance, replace `n = (offset <= 256) ? 0 : 7` with the
/// equivalent (for offset <= 536871168) `n = (256 - offset) >> 29`.
///
/// **The `(256 - offset) >> 29` is an UNSIGNED wrap and an unsigned shift.** In C
/// `256 - offset` on `u32` wraps to a huge value whenever `offset > 256`, and
/// `>> 29` of that is 7; for `offset <= 256` the difference is small and non-negative
/// so the shift is 0. `wrapping_sub` reproduces exactly that — an `i32` subtraction
/// with an arithmetic shift would give -1, not 7, and every long-offset match would
/// be assigned the wrong slot.
#[inline(always)]
#[allow(
    clippy::manual_range_contains,
    reason = "C: ASSERT(offset >= 1 && offset <= 32768) — kept spelling-for-spelling"
)]
pub(crate) fn deflate_get_offset_slot(offset: u32) -> u32 {
    let n = 256u32.wrapping_sub(offset) >> 29;

    debug_assert!(offset >= 1 && offset <= DEFLATE_MAX_MATCH_OFFSET);

    DEFLATE_OFFSET_SLOT[((offset - 1) >> n) as usize] as u32 + (n << 1)
}

#[cfg(test)]
mod tests {
    use super::super::DEFLATE_MIN_MATCH_LEN;
    use super::*;

    /// `deflate_length_slot` is a reverse map of `deflate_length_slot_base`. Derive
    /// it and compare, rather than eyeballing 259 transcribed entries: the slot for a
    /// length is the unique slot whose base range contains it.
    #[test]
    fn length_slot_map_is_the_reverse_of_the_base_table() {
        for len in DEFLATE_MIN_MATCH_LEN..=DEFLATE_MAX_MATCH_LEN {
            // The last slot whose base is <= len.
            let want = DEFLATE_LENGTH_SLOT_BASE
                .iter()
                .rposition(|&base| base <= len)
                .expect("every valid length has a slot");
            assert_eq!(
                DEFLATE_LENGTH_SLOT[len as usize], want as u8,
                "len={len}: table says {}, derived {want}",
                DEFLATE_LENGTH_SLOT[len as usize]
            );
        }
    }

    /// Every length in a slot must fit in that slot's extra bits, and the slot must
    /// cover exactly `1 << extra_bits` lengths (except the final 258-only slot).
    #[test]
    fn length_slots_fit_their_extra_bits() {
        for len in DEFLATE_MIN_MATCH_LEN..=DEFLATE_MAX_MATCH_LEN {
            let slot = DEFLATE_LENGTH_SLOT[len as usize] as usize;
            let extra = len - DEFLATE_LENGTH_SLOT_BASE[slot];
            let bits = DEFLATE_EXTRA_LENGTH_BITS[slot] as u32;
            assert!(
                extra < (1u32 << bits),
                "len={len} slot={slot}: extra={extra} does not fit in {bits} bits"
            );
        }
        // Slot 28 is length 258 alone, with zero extra bits — the format's one
        // irregularity, and the reason the table is not a closed formula.
        assert_eq!(DEFLATE_LENGTH_SLOT[258], 28);
        assert_eq!(DEFLATE_LENGTH_SLOT_BASE[28], 258);
        assert_eq!(DEFLATE_EXTRA_LENGTH_BITS[28], 0);
    }

    /// `deflate_get_offset_slot` must agree with the offset base table over the WHOLE
    /// legal range 1..=32768 — including the `n = 7` branch, which is where the
    /// unsigned-wrap trick lives and where a signed shift would silently diverge.
    #[test]
    fn offset_slot_matches_the_base_table_over_the_full_range() {
        for offset in 1..=DEFLATE_MAX_MATCH_OFFSET {
            let want = DEFLATE_OFFSET_SLOT_BASE
                .iter()
                .rposition(|&base| base <= offset)
                .expect("every valid offset has a slot") as u32;
            assert_eq!(deflate_get_offset_slot(offset), want, "offset={offset}");

            let slot = want as usize;
            let extra = offset - DEFLATE_OFFSET_SLOT_BASE[slot];
            let bits = DEFLATE_EXTRA_OFFSET_BITS[slot] as u32;
            assert!(
                extra < (1u32 << bits),
                "offset={offset} slot={slot}: extra={extra} exceeds {bits} bits"
            );
        }
    }

    /// The `n = (256 - offset) >> 29` trick: 0 for offset <= 256, 7 above it. Pin the
    /// boundary explicitly — this is the one line where a `wrapping_sub` -> `-` slip
    /// would compile and be wrong only for large offsets.
    #[test]
    fn offset_slot_shift_selector_switches_at_256() {
        for offset in [1u32, 2, 255, 256, 257, 258, 32768] {
            let n = 256u32.wrapping_sub(offset) >> 29;
            assert_eq!(n, if offset <= 256 { 0 } else { 7 }, "offset={offset}");
        }
    }

    /// The permutation must be a permutation of 0..19, and the precode extra-bit
    /// table must give extra bits to exactly symbols 16, 17, 18.
    #[test]
    fn precode_tables_are_well_formed() {
        let mut seen = [false; DEFLATE_NUM_PRECODE_SYMS];
        for &p in DEFLATE_PRECODE_LENS_PERMUTATION.iter() {
            assert!(!seen[p as usize], "duplicate {p} in the permutation");
            seen[p as usize] = true;
        }
        assert!(seen.iter().all(|&s| s));

        for (sym, &bits) in DEFLATE_EXTRA_PRECODE_BITS.iter().enumerate() {
            let want = match sym {
                16 => 2,
                17 => 3,
                18 => 7,
                _ => 0,
            };
            assert_eq!(bits, want, "precode sym {sym}");
        }
    }
}
