#!/usr/bin/env bash
# off_cpu_profile.sh — capture off-CPU flamegraph showing where threads
# are SLEEPING (lock waits, channel recvs, page-fault stalls).
#
# Per docs/PARALLEL_PROFILING_PLAN.md §3: a normal perf record samples
# the running thread at 999 Hz and misses where threads are BLOCKED.
# When parallel scaling falls off, the threads aren't computing — they're
# waiting. Off-CPU profiling captures the waits as their own flame
# graph.
#
# Linux-only. Requires sudo for sched events (or proc.kptr_restrict=0
# + kernel.perf_event_paranoid=1 sysctls).
#
# Usage:
#   scripts/off_cpu_profile.sh \
#       --compressed benchmark_data/silesia-large.gz \
#       --gzippy    target/release/gzippy \
#       --threads   16 \
#       [--rapidgzip vendor/.../rapidgzip]   # if set, also profiles vendor for comparison
#       [--out-dir docs/runs/offcpu-TIMESTAMP]
#
# Outputs:
#   $OUT_DIR/gzippy.offcpu.svg     (flame graph: sleeping time)
#   $OUT_DIR/gzippy.oncpu.svg      (flame graph: running time, for comparison)
#   [if --rapidgzip:] $OUT_DIR/rapidgzip.offcpu.svg + .oncpu.svg

set -euo pipefail

# --help works on any OS.
for arg in "$@"; do
  if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
    sed -n '3,26p' "$0" >&2
    exit 0
  fi
done

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "ERROR: this script needs Linux + perf. Run on neurotic." >&2
  exit 2
fi

if ! command -v perf >/dev/null; then
  echo "ERROR: perf not installed (apt install linux-perf-tools)" >&2
  exit 2
fi

COMPRESSED=""
GZIPPY=""
RAPIDGZIP=""
THREADS=16
OUT_DIR=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --compressed) COMPRESSED="$2"; shift 2 ;;
    --gzippy)     GZIPPY="$2"; shift 2 ;;
    --rapidgzip)  RAPIDGZIP="$2"; shift 2 ;;
    --threads)    THREADS="$2"; shift 2 ;;
    --out-dir)    OUT_DIR="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -n "$COMPRESSED" && -n "$GZIPPY" ]] || {
  echo "ERROR: --compressed and --gzippy required" >&2
  exit 2
}
[[ -n "$OUT_DIR" ]] || OUT_DIR="docs/runs/offcpu-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$OUT_DIR"

# Pick a flamegraph tool. inferno preferred (Rust port, no Perl).
FLAMEGRAPH_TOOL=""
if command -v inferno-collapse-perf >/dev/null && command -v inferno-flamegraph >/dev/null; then
  FLAMEGRAPH_TOOL="inferno"
elif command -v flamegraph.pl >/dev/null; then
  FLAMEGRAPH_TOOL="perl"
else
  echo "WARN: no flamegraph tool found (cargo install inferno or clone brendangregg/FlameGraph)" >&2
  echo "      Raw perf.data files will be produced but no SVG." >&2
fi

profile_binary() {
  local label="$1"
  local bin="$2"
  shift 2
  local args=("$@")

  echo "" >&2
  echo "[on-CPU] $label" >&2
  perf record -F 999 --call-graph=dwarf -o "$OUT_DIR/$label.oncpu.data" -- \
    "$bin" "${args[@]}" < "$COMPRESSED" > /dev/null 2>>"$OUT_DIR/perf.stderr"

  echo "[off-CPU] $label (sched + sleep events)" >&2
  # sched:sched_switch fires on context switches; we get stack at switch-out time.
  # This requires root or kernel.perf_event_paranoid <= -1.
  perf record -e sched:sched_switch \
              --call-graph=dwarf \
              -o "$OUT_DIR/$label.offcpu.data" -- \
    "$bin" "${args[@]}" < "$COMPRESSED" > /dev/null 2>>"$OUT_DIR/perf.stderr"

  if [[ "$FLAMEGRAPH_TOOL" == "inferno" ]]; then
    perf script -i "$OUT_DIR/$label.oncpu.data" 2>>"$OUT_DIR/perf.stderr" | \
      inferno-collapse-perf > "$OUT_DIR/$label.oncpu.folded"
    inferno-flamegraph --title "$label on-CPU" < "$OUT_DIR/$label.oncpu.folded" \
      > "$OUT_DIR/$label.oncpu.svg"

    perf script -i "$OUT_DIR/$label.offcpu.data" 2>>"$OUT_DIR/perf.stderr" | \
      inferno-collapse-perf > "$OUT_DIR/$label.offcpu.folded"
    inferno-flamegraph --title "$label off-CPU (sleep time)" --countname "us" \
      < "$OUT_DIR/$label.offcpu.folded" > "$OUT_DIR/$label.offcpu.svg"
    echo "  → $OUT_DIR/$label.oncpu.svg" >&2
    echo "  → $OUT_DIR/$label.offcpu.svg" >&2
  elif [[ "$FLAMEGRAPH_TOOL" == "perl" ]]; then
    perf script -i "$OUT_DIR/$label.oncpu.data" 2>>"$OUT_DIR/perf.stderr" | \
      stackcollapse-perf.pl > "$OUT_DIR/$label.oncpu.folded"
    flamegraph.pl --title "$label on-CPU" "$OUT_DIR/$label.oncpu.folded" > "$OUT_DIR/$label.oncpu.svg"
    perf script -i "$OUT_DIR/$label.offcpu.data" 2>>"$OUT_DIR/perf.stderr" | \
      stackcollapse-perf.pl > "$OUT_DIR/$label.offcpu.folded"
    flamegraph.pl --title "$label off-CPU (sleep time)" --countname us \
      "$OUT_DIR/$label.offcpu.folded" > "$OUT_DIR/$label.offcpu.svg"
  fi
}

profile_binary gzippy "$GZIPPY" -d --processes "$THREADS"

if [[ -n "$RAPIDGZIP" ]]; then
  profile_binary rapidgzip "$RAPIDGZIP" -d -P "$THREADS"
fi

# Summary doc — pair the on/off SVGs.
{
  echo "# Off-CPU profile bundle"
  echo ""
  echo "Generated by \`scripts/off_cpu_profile.sh\`. Open the SVGs in a browser."
  echo ""
  echo "## What to look for in the off-CPU flamegraph"
  echo ""
  echo "- Wide flame at \`std::sync::mpsc::Receiver::recv\` → consumer blocked on workers."
  echo "- Wide flame at \`parking_lot::Mutex::lock_slow\` or \`futex_wait\` → lock contention."
  echo "- Wide flame at \`__do_page_fault\` or \`handle_mm_fault\` → page-zero stalls."
  echo "- Wide flame at \`schedule\` → just generic block, look at parent for cause."
  echo ""
  echo "## Files"
  echo ""
  for f in "$OUT_DIR"/*.svg; do
    [[ -e "$f" ]] || continue
    echo "- \`$(basename "$f")\`"
  done
} > "$OUT_DIR/README.md"

echo "" >&2
echo "=== done ===" >&2
echo "Bundle: $OUT_DIR/README.md" >&2
