#!/usr/bin/env bash
# regen-index.sh — DERIVE every README from the SCORE: lines. ZERO new numbers.
#
# This script is a dumb grep+awk over the one-line `SCORE:` headers in every
# cell file. It regenerates the content between
#   <!-- BEGIN GENERATED --> ... <!-- END GENERATED -->
# in score/README.md and each per-box README. It NEVER reads the yaml/prose, so
# the SCORE: line is the single source of derived truth (see SCHEMA.md).
#
# Usage:  score/regen-index.sh        (run from repo root or anywhere)
set -euo pipefail

SCORE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCORE_DIR"

ARCHES=(intel-x86_64 amd-x86_64)
THREADS=(t1 t4 t8 t12 t16)
CORPORA=(model monorepo storedheavy silesia bignasa)
HEAD_SHA="$(git rev-parse --short=7 HEAD 2>/dev/null || echo UNKNOWN)"

# --- gather SCORE lines from CANONICAL cell files only (no docs/archive) ----
TSV="$(mktemp)"
trap 'rm -f "$TSV"' EXIT
# fields: arch tN corpus native_ratio native_verdict isal_ratio isal_verdict rg_ms N date blindtags
for arch in "${ARCHES[@]}"; do for t in "${THREADS[@]}"; do for c in "${CORPORA[@]}"; do
  cell="$SCORE_DIR/$arch/$t/$c.md"
  [ -f "$cell" ] || continue
  line="$(grep -m1 '^SCORE:' "$cell" 2>/dev/null || true)"
  [ -n "$line" ] || continue
  body="${line#SCORE: }"
  arch=$(awk '{print $1}' <<<"$body")
  tn=$(awk '{print $2}'   <<<"$body")
  corpus=$(awk '{print $3}' <<<"$body")
  nat=$(sed -nE 's/.*native=([0-9.]+) (PASS|FAIL).*/\1/p' <<<"$body")
  natv=$(sed -nE 's/.*native=[0-9.]+ (PASS|FAIL).*/\1/p' <<<"$body")
  isal=$(sed -nE 's/.*isal=([0-9.]+) (PASS|FAIL).*/\1/p' <<<"$body")
  isalv=$(sed -nE 's/.*isal=[0-9.]+ (PASS|FAIL).*/\1/p' <<<"$body")
  rg=$(sed -nE 's/.*rg=([0-9.]+)ms.*/\1/p' <<<"$body")
  n=$(sed -nE 's/.*N=([0-9]+).*/\1/p' <<<"$body")
  date=$(sed -nE 's/.*frozen ([0-9-]+).*/\1/p' <<<"$body")
  blind=$(sed -nE 's/.*blind:(.*)$/\1/p' <<<"$body")
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$arch" "$tn" "$corpus" "${nat:-?}" "${natv:-?}" "${isal:-?}" "${isalv:-?}" "${rg:-?}" "${n:-0}" "${date:-?}" "${blind:-}" >> "$TSV"
done; done; done

CELLS_PRESENT=$(wc -l < "$TSV" | tr -d ' ')
CELLS_EXPECTED=$(( ${#ARCHES[@]} * ${#THREADS[@]} * ${#CORPORA[@]} ))

# --- helper: emit a blindspot tag value from the blind string -------------
tagval() { sed -nE "s/.*(^|,)$1=([^,]*).*/\2/p" <<<"$2"; }

# --- BUILD the generated markdown into a variable --------------------------
gen() {
  echo "<!-- regenerated by score/regen-index.sh — DO NOT EDIT BY HAND -->"
  echo "_Derived $(date -u +%Y-%m-%dT%H:%MZ) from ${CELLS_PRESENT}/${CELLS_EXPECTED} cells. HEAD=${HEAD_SHA}._"
  echo

  # ---- Full matrix table (per arch) ----
  for arch in "${ARCHES[@]}"; do
    echo "### ${arch} — matrix (native / isal ratio vs rapidgzip)"
    echo
    printf '| corpus |'; for t in "${THREADS[@]}"; do printf ' %s |' "$t"; done; echo
    printf '|---|'; for _ in "${THREADS[@]}"; do printf '%s' '---|'; done; echo
    for c in "${CORPORA[@]}"; do
      printf '| %s |' "$c"
      for t in "${THREADS[@]}"; do
        row=$(awk -F'\t' -v a="$arch" -v t="$t" -v c="$c" '$1==a&&$2==t&&$3==c{print;exit}' "$TSV")
        if [ -z "$row" ]; then printf ' · |'; else
          nat=$(cut -f4 <<<"$row"); isal=$(cut -f6 <<<"$row")
          printf ' n%s/i%s |' "$nat" "$isal"
        fi
      done
      echo
    done
    echo
  done

  # ---- View 1: coverage holes ----
  echo "### Blindspot 1 — coverage holes (expected cells with no SCORE line)"
  echo
  holes=0
  for arch in "${ARCHES[@]}"; do for t in "${THREADS[@]}"; do for c in "${CORPORA[@]}"; do
    if ! awk -F'\t' -v a="$arch" -v t="$t" -v c="$c" '$1==a&&$2==t&&$3==c{f=1}END{exit !f}' "$TSV"; then
      echo "- MISSING: ${arch}/${t}/${c}"; holes=$((holes+1))
    fi
  done; done; done
  [ "$holes" -eq 0 ] && echo "- none — matrix fully populated."
  echo

  # ---- View 2: worst-session-binding (per cell, which build binds + lever) ----
  echo "### Blindspot 2 — binding constraint per filled cell"
  echo
  echo "| cell | native | isal | binds | lever |"
  echo "|---|---|---|---|---|"
  while IFS=$'\t' read -r arch t c nat natv isal isalv rg n date blind; do
    [ "$arch" = "?" ] && continue
    if [ "$natv" = PASS ] && [ "$isalv" = PASS ]; then binds="none (both pass)"
    elif [ "$natv" = FAIL ] && [ "$isalv" = PASS ]; then binds="isal-only (native blocks drop)"
    elif [ "$natv" = PASS ] && [ "$isalv" = FAIL ]; then binds="native-only"
    else binds="BOTH FAIL"; fi
    lever=$(tagval lever "$blind")
    echo "| ${arch}/${t}/${c} | ${nat} ${natv} | ${isal} ${isalv} | ${binds} | ${lever:-?} |"
  done < "$TSV"
  echo

  # ---- View 3: cross-arch divergence (same t×corpus, native verdict differs) ----
  echo "### Blindspot 3 — cross-arch divergence (native PASS on one arch, FAIL on other)"
  echo
  div=0
  for t in "${THREADS[@]}"; do for c in "${CORPORA[@]}"; do
    iv=$(awk -F'\t' -v t="$t" -v c="$c" '$1=="intel-x86_64"&&$2==t&&$3==c{print $5}' "$TSV")
    av=$(awk -F'\t' -v t="$t" -v c="$c" '$1=="amd-x86_64"&&$2==t&&$3==c{print $5}' "$TSV")
    if [ -n "$iv" ] && [ -n "$av" ] && [ "$iv" != "$av" ]; then
      echo "- ${t}/${c}: intel native=${iv}, amd native=${av} (the drop-isal fork lives here)"; div=$((div+1))
    fi
  done; done
  [ "$div" -eq 0 ] && echo "- none observed among cells present on BOTH arches."
  echo

  # ---- View 4: staleness (src sha != HEAD) ----
  echo "### Blindspot 4 — staleness (binaries built at src != HEAD ${HEAD_SHA})"
  echo
  stale=0
  while IFS=$'\t' read -r arch t c nat natv isal isalv rg n date blind; do
    [ "$arch" = "?" ] && continue
    src=$(tagval src "$blind")
    if [ -n "$src" ] && [ "$src" != "$HEAD_SHA" ]; then
      echo "- ${arch}/${t}/${c}: src=${src} != HEAD ${HEAD_SHA} (re-verify before trusting)"; stale=$((stale+1))
    fi
  done < "$TSV"
  [ "$stale" -eq 0 ] && echo "- none — all present cells built at HEAD."
  echo

  # ---- View 5: untrustworthy distribution (dist != RESOLVED or N<3) ----
  echo "### Blindspot 5 — untrustworthy distribution (dist!=RESOLVED or N<3)"
  echo
  unt=0
  while IFS=$'\t' read -r arch t c nat natv isal isalv rg n date blind; do
    [ "$arch" = "?" ] && continue
    dist=$(tagval dist "$blind")
    if { [ -n "$dist" ] && [ "$dist" != RESOLVED ]; } || [ "${n:-0}" -lt 3 ]; then
      echo "- ${arch}/${t}/${c}: dist=${dist:-?} N=${n} (treat as provisional)"; unt=$((unt+1))
    fi
  done < "$TSV"
  [ "$unt" -eq 0 ] && echo "- none — all present cells RESOLVED with N>=3."
  echo

  # ---- Lever rollup ----
  echo "### Lever rollup (count of dominant lever across filled cells)"
  echo
  if [ "$CELLS_PRESENT" -gt 0 ]; then
    while IFS=$'\t' read -r arch t c nat natv isal isalv rg n date blind; do
      [ "$arch" = "?" ] && continue
      tagval lever "$blind"
    done < "$TSV" | sed '/^$/d' | sort | uniq -c | sort -rn | while read -r cnt lev; do
      echo "- ${lev}: ${cnt} cell(s)"
    done
  else
    echo "- (no cells yet)"
  fi
  echo
}

# --- splice generated block into a README between the markers --------------
splice() {
  local file="$1"
  [ -f "$file" ] || { echo "skip (missing): $file" >&2; return; }
  local tmp; tmp="$(mktemp)"
  awk '
    /<!-- BEGIN GENERATED -->/ {print; system("cat /dev/stdin"); skip=1; next}
    /<!-- END GENERATED -->/   {print; skip=0; next}
    !skip {print}
  ' "$file" > "$tmp" < <(gen)
  mv "$tmp" "$file"
  echo "regenerated: $file"
}

splice "$SCORE_DIR/README.md"
# per-box READMEs get the same global generated block (cheap; reader filters by arch)
splice "$SCORE_DIR/intel-x86_64/README.md"
splice "$SCORE_DIR/amd-x86_64/README.md"

echo "done: ${CELLS_PRESENT}/${CELLS_EXPECTED} cells indexed."
